# Generated by Django 6.0.5 on 2026-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
