# Generated by Django 6.0.5 on 2026-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_repetitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='success',
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='grade',
            field=models.CharField(default='medio', max_length=10),
        ),
    ]
